name: Build Django App for Feature Branch

on:
  push:
    branches:
      - feature/* # Trigger on pushes to any branch starting with "feature/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        run: sudo apt-get update && sudo apt-get install -y docker.io

      # Step 3: Build the Docker image
      - name: Build Docker image for feature
        run: docker build -t feature_${{ github.head_ref }} .

      # Step 4: Save the Docker image as an artifact (for later use)
      - name: Save Docker image
        uses: actions/upload-artifact@v3
        with:
          name: feature_${{ github.head_ref }}_image
          path: |
            ./ # Adjust to your Docker image tar path if necessary
