name: Build and Test Django App

on:
  push:
    branches:
      - feature/* # Trigger on pushes to any branch starting with "feature/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t feature_image:${{ github.sha }} .

      # Run the container
      - name: Test Docker container
        run: |
          docker run -d -p 8000:8000 feature_image:${{ github.sha }}
          sleep 10
          curl -f http://localhost:8000
