name: Build Django App for Feature Branch

on:
  push:
    branches:
      - feature/* # Trigger on pushes to any branch starting with "feature/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Use Docker Buildx Action
      - name: Prepare Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for feature
        run: docker buildx build --platform linux/amd64 -t feature_${{ github.head_ref }} .

      # Save the Docker image as an artifact (for later use)
      - name: Save Docker image
        uses: actions/upload-artifact@v3
        with:
          name: feature_${{ github.head_ref }}_image
          path: |
            ./